workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(ISSUER_ID)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(KEY_ID)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(PRIVATE_KEY)
        APP_STORE_CONNECT_KEY_CONTENT: $APP_STORE_CONNECT_PRIVATE_KEY
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: "<lee@johndrows.net>"
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: false
        submit_to_app_store: true
