platform :ios, '13.0'
use_frameworks! :linkage => :static
use_modular_headers!

flutter_application_path = '../'

target 'Runner' do
  config = ENV['CONFIGURATION'] || 'Release'
  engine_podspec = File.expand_path(File.join(__dir__, 'Flutter', config, 'Flutter.podspec'))
  unless File.exist?(engine_podspec)
    abort("❌ Missing #{engine_podspec}. Run: flutter build ios-framework --cocoapods --output=ios/Flutter")
  end
  pod 'Flutter', :podspec => engine_podspec

  plugin_file = File.expand_path(File.join(flutter_application_path, '.flutter-plugins-dependencies'))
  if File.exist?(plugin_file)
    require 'json'
    ios_plugins = (JSON.parse(File.read(plugin_file))['plugins'] || {})['ios'] || []
    ios_plugins.each do |p|
      pod p['name'], :path => File.expand_path(File.join(flutter_application_path, p['path'], 'ios'))
    end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      c.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
