name: iOS Build

on:
  push:
    branches:
      - ios_build
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Get Flutter Dependencies
        run: |
          flutter pub get

      - name: Precache iOS Artifacts
        run: |
          flutter precache --ios

      - name: Run Pod Install
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS App
        run: |
          flutter build ios --debug --no-codesign
