name: iOS Build (Powerless Over Cars)

on:
  push:
    branches:
      - ios_build
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Verify Flutter Installation
        run: flutter --version

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Precache iOS Engine
        run: flutter precache --ios

      - name: Build iOS App (No Code Sign)
        run: flutter build ios --release --no-codesign

      - name: Archive Build Output
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-build
          path: build/ios/iphoneos/Runner.app
